# ======================
# FRONTEND BUILD
# ======================
FROM node:18 AS frontend-builder

WORKDIR /app

COPY apps/playground/package*.json ./apps/playground/
WORKDIR /app/apps/playground
RUN npm install

# copy source
COPY apps/playground ./apps/playground

# build output to /app/apps/playground/out
RUN npm run build


# ======================
# SERVER RUNTIME
# ======================
FROM node:18 AS runtime

WORKDIR /app

# copy server
COPY server/package*.json ./server/
WORKDIR /app/server
RUN npm install --omit=dev

# copy server source
COPY server ./server

# copy frontend output to root (karena server nyari ../index.html)
COPY --from=frontend-builder /app/apps/playground/out /app/

WORKDIR /app/server

EXPOSE 3000

CMD ["node", "index.js"]
